version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm run build
 post_build:
   commands:
     - aws s3 sync --delete . "s3://www.alexandermoreton.co.uk"