version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - aws s3 rm "s3://alexandermoreton.co.uk/public" --recursive
 build:
   commands:
     - aws s3 sync --delete ./public  "s3://alexandermoreton.co.uk"
 post_build:
   commands:
     - echo "post_build step"